title: Reaction Group
email: info@reaction-grp.com
description: Nationwide electrical and fire compliance specialists.
baseurl: "/React-Group-James" # THIS MUST MATCH YOUR REPO NAME EXACTLY
url: "https://LD1878.github.io" 
theme: minima
plugins:
  - jekyll-seo-tag
future: true
